
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/musimeter
    networks:
      - musimeter_network
    restart: unless-stopped

  mongodb:
    image: mongo:6
    container_name: mongodb

    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: musimeter
    networks:
      - musimeter_network

  

volumes:
  mongodb_data:

networks:
  musimeter_network:
    driver: bridge
