version: '3.8'

name: sportimetrics

services:
  mongo: 
    image: mongo:7.0.12
    volumes:
      - mongo_data:/data/db
    networks:
      - spotiapp
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    networks:
      - spotiapp
    depends_on:
      - mongo

volumes:
  mongo_data:

networks:
  spotiapp:
    driver: bridge