
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    expose:
      - "3000"  # Expose port 3000 to the internal network
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/musimeter
    networks:
      - musimeter_network
    restart: unless-stopped

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: musimeter
    networks:
      - musimeter_network

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - musimeter_network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  musimeter_network:
    driver: bridge
