
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/musimeter
    networks:
      - musimeter_network
    restart: unless-stopped

  mongodb:
    image: mongo:6
    container_name: mongodb

    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: musimeter
    networks:
      - musimeter_network

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    depends_on:
      - app
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - musimeter_network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  musimeter_network:
    driver: bridge
