export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
// UX
export const ERROR = "ERROR";
export const SUCCESS = "SUCCESS";
export const CLOSE_DISPLAY = "CLOSE_DISPLAY"

export const SHOW_COOKIE_PREFERENCES = "SHOW_COOKIE_PREFERENCES"
export const HIDE_COOKIE_PREFERENCES = "HIDE_COOKIE_PREFERENCES"